---
- hosts: Application Servers
  sudo: True
  user: root

  tasks:

    - action: template src=bash/.bash_profile_app dest=/tmp/.bash_profile
    - action: shell cp -f /tmp/.bash_profile /home/bhoward/.bash_profile
    - file: path=/home/bhoward/.bash_profile owner=bhoward
    - action: shell cp -f /tmp/.bash_profile /home/bmckenna/.bash_profile
    - file: path=/home/bmckenna/.bash_profile owner=bmckenna
    - action: shell cp -f /tmp/.bash_profile /home/bswaminathan/.bash_profile
    - file: path=/home/bswaminathan/.bash_profile owner=bswaminathan
    - action: shell cp -f /tmp/.bash_profile /home/mgoodfellow/.bash_profile
    - file: path=/home/mgoodfellow/.bash_profile owner=mgoodfellow
    - action: shell cp -f /tmp/.bash_profile /home/mhartman/.bash_profile
    - file: path=/home/mhartman/.bash_profile owner=mhartman
    - action: shell cp -f /tmp/.bash_profile /home/oracle/.bash_profile
    - file: path=/home/oracle/.bash_profile owner=oracle
    - action: shell cp -f /tmp/.bash_profile /home/twalton/.bash_profile
    - file: path=/home/twalton/.bash_profile owner=twalton
    - action: shell cp -f /tmp/.bash_profile /home/gurias/.bash_profile
    - file: path=/home/gurias/.bash_profile owner=gurias
    - action: shell cp -f /tmp/.bash_profile /home/gpage/.bash_profile
    - file: path=/home/gpage/.bash_profile owner=gpage
    - action: shell cp -f /tmp/.bash_profile /home/jestapa/.bash_profile
    - file: path=/home/jestapa/.bash_profile owner=jestapa
    - action: shell cp -f /tmp/.bash_profile /home/kmcdonnell/.bash_profile
    - file: path=/home/kmcdonnell/.bash_profile owner=kmcdonnell
    - action: shell cp -f /tmp/.bash_profile /home/rrisius/.bash_profile
    - file: path=/home/rrisius/.bash_profile owner=rrisius
    - action: shell cp -f /tmp/.bash_profile /home/kslaugh/.bash_profile
    - file: path=/home/kslaugh/.bash_profile owner=kslaugh


- hosts: oradev01.corp.ruan.com
  sudo: True
  user: root

  tasks:

    - action: template src=bash/.bash_profile_oracle dest=/tmp/.bash_profile
    - action: shell cp -f /tmp/.bash_profile /home/bhoward/.bash_profile
    - file: path=/home/bhoward/.bash_profile owner=bhoward
    - action: shell cp -f /tmp/.bash_profile /home/bmckenna/.bash_profile
    - file: path=/home/bmckenna/.bash_profile owner=bmckenna
    - action: shell cp -f /tmp/.bash_profile /home/bswaminathan/.bash_profile
    - file: path=/home/bswaminathan/.bash_profile owner=bswaminathan
    - action: shell cp -f /tmp/.bash_profile /home/mgoodfellow/.bash_profile
    - file: path=/home/mgoodfellow/.bash_profile owner=mgoodfellow
    - action: shell cp -f /tmp/.bash_profile /home/mhartman/.bash_profile
    - file: path=/home/mhartman/.bash_profile owner=mhartman
    - action: shell cp -f /tmp/.bash_profile /home/oracle/.bash_profile
    - file: path=/home/oracle/.bash_profile owner=oracle
    - action: shell cp -f /tmp/.bash_profile /home/twalton/.bash_profile
    - file: path=/home/twalton/.bash_profile owner=twalton
    - action: shell cp -f /tmp/.bash_profile /home/gurias/.bash_profile
    - file: path=/home/gurias/.bash_profile owner=gurias
    - action: shell cp -f /tmp/.bash_profile /home/gpage/.bash_profile
    - file: path=/home/gpage/.bash_profile owner=gpage
    - action: shell cp -f /tmp/.bash_profile /home/jestapa/.bash_profile
    - file: path=/home/jestapa/.bash_profile owner=jestapa
    - action: shell cp -f /tmp/.bash_profile /home/kmcdonnell/.bash_profile
    - file: path=/home/kmcdonnell/.bash_profile owner=kmcdonnell
    - action: shell cp -f /tmp/.bash_profile /home/rrisius/.bash_profile
    - file: path=/home/rrisius/.bash_profile owner=rrisius
    - action: shell cp -f /tmp/.bash_profile /home/kslaugh/.bash_profile
    - file: path=/home/kslaugh/.bash_profile owner=kslaugh

  hosts: otmftidev01.corp.ruan.com
  sudo: True
  user: root

  tasks:

    - action: template src=bash/.bash_profile_oracle_fti dest=/tmp/.bash_profile
    - action: shell cp -f /tmp/.bash_profile /home/bhoward/.bash_profile
    - file: path=/home/bhoward/.bash_profile owner=bhoward
    - action: shell cp -f /tmp/.bash_profile /home/bmckenna/.bash_profile
    - file: path=/home/bmckenna/.bash_profile owner=bmckenna
    - action: shell cp -f /tmp/.bash_profile /home/bswaminathan/.bash_profile
    - file: path=/home/bswaminathan/.bash_profile owner=bswaminathan
    - action: shell cp -f /tmp/.bash_profile /home/mgoodfellow/.bash_profile
    - file: path=/home/mgoodfellow/.bash_profile owner=mgoodfellow
    - action: shell cp -f /tmp/.bash_profile /home/mhartman/.bash_profile
    - file: path=/home/mhartman/.bash_profile owner=mhartman
    - action: shell cp -f /tmp/.bash_profile /home/oracle/.bash_profile
    - file: path=/home/oracle/.bash_profile owner=oracle
    - action: shell cp -f /tmp/.bash_profile /home/twalton/.bash_profile
    - file: path=/home/twalton/.bash_profile owner=twalton
    - action: shell cp -f /tmp/.bash_profile /home/gurias/.bash_profile
    - file: path=/home/gurias/.bash_profile owner=gurias
    - action: shell cp -f /tmp/.bash_profile /home/gpage/.bash_profile
    - file: path=/home/gpage/.bash_profile owner=gpage
    - action: shell cp -f /tmp/.bash_profile /home/jestapa/.bash_profile
    - file: path=/home/jestapa/.bash_profile owner=jestapa
    - action: shell cp -f /tmp/.bash_profile /home/kmcdonnell/.bash_profile
    - file: path=/home/kmcdonnell/.bash_profile owner=kmcdonnell
    - action: shell cp -f /tmp/.bash_profile /home/rrisius/.bash_profile
    - file: path=/home/rrisius/.bash_profile owner=rrisius
    - action: shell cp -f /tmp/.bash_profile /home/kslaugh/.bash_profile
    - file: path=/home/kslaugh/.bash_profile owner=kslaugh

- hosts: Fusion Application Servers
  sudo: True
  user: root

  tasks:

    - action: template src=bash/.bash_profile_fti dest=/tmp/.bash_profile
    - action: shell cp -f /tmp/.bash_profile /home/bhoward/.bash_profile
    - file: path=/home/bhoward/.bash_profile owner=bhoward
    - action: shell cp -f /tmp/.bash_profile /home/bmckenna/.bash_profile
    - file: path=/home/bmckenna/.bash_profile owner=bmckenna
    - action: shell cp -f /tmp/.bash_profile /home/bswaminathan/.bash_profile
    - file: path=/home/bswaminathan/.bash_profile owner=bswaminathan
    - file: path=/home/mgoodfellow/.bash_profile owner=mgoodfellow
    - action: shell cp -f /tmp/.bash_profile /home/mhartman/.bash_profile
    - file: path=/home/mhartman/.bash_profile owner=mhartman
    - action: shell cp -f /tmp/.bash_profile /home/oracle/.bash_profile
    - file: path=/home/oracle/.bash_profile owner=oracle
    - file: path=/home/twalton/.bash_profile owner=twalton
    - action: shell cp -f /tmp/.bash_profile /home/gurias/.bash_profile
    - file: path=/home/gurias/.bash_profile owner=gurias
    - action: shell cp -f /tmp/.bash_profile /home/gpage/.bash_profile
    - file: path=/home/gpage/.bash_profile owner=gpage
    - action: shell cp -f /tmp/.bash_profile /home/jestapa/.bash_profile
    - file: path=/home/jestapa/.bash_profile owner=jestapa
    - action: shell cp -f /tmp/.bash_profile /home/kmcdonnell/.bash_profile
    - file: path=/home/kmcdonnell/.bash_profile owner=kmcdonnell
    - action: shell cp -f /tmp/.bash_profile /home/rrisius/.bash_profile
    - file: path=/home/rrisius/.bash_profile owner=rrisius
    - action: shell cp -f /tmp/.bash_profile /home/kslaugh/.bash_profile
    - file: path=/home/kslaugh/.bash_profile owner=kslaugh

- hosts: Web Servers 
  sudo: True
  user: root

  tasks:

    - action: template src=bash/.bash_profile_web dest=/tmp/.bash_profile
    - action: shell cp -f /tmp/.bash_profile /home/bhoward/.bash_profile
    - file: path=/home/bhoward/.bash_profile owner=bhoward
    - action: shell cp -f /tmp/.bash_profile /home/bmckenna/.bash_profile
    - file: path=/home/bmckenna/.bash_profile owner=bmckenna
    - action: shell cp -f /tmp/.bash_profile /home/bswaminathan/.bash_profile
    - file: path=/home/bswaminathan/.bash_profile owner=bswaminathan
    - action: shell cp -f /tmp/.bash_profile /home/mgoodfellow/.bash_profile
    - file: path=/home/mgoodfellow/.bash_profile owner=mgoodfellow
    - action: shell cp -f /tmp/.bash_profile /home/mhartman/.bash_profile
    - file: path=/home/mhartman/.bash_profile owner=mhartman
    - action: shell cp -f /tmp/.bash_profile /home/oracle/.bash_profile
    - file: path=/home/oracle/.bash_profile owner=oracle
    - action: shell cp -f /tmp/.bash_profile /home/twalton/.bash_profile
    - file: path=/home/twalton/.bash_profile owner=twalton
    - action: shell cp -f /tmp/.bash_profile /home/gurias/.bash_profile
    - file: path=/home/gurias/.bash_profile owner=gurias
    - action: shell cp -f /tmp/.bash_profile /home/gpage/.bash_profile
    - file: path=/home/gpage/.bash_profile owner=gpage
    - action: shell cp -f /tmp/.bash_profile /home/jestapa/.bash_profile
    - file: path=/home/jestapa/.bash_profile owner=jestapa
    - action: shell cp -f /tmp/.bash_profile /home/kmcdonnell/.bash_profile
    - file: path=/home/kmcdonnell/.bash_profile owner=kmcdonnell
    - action: shell cp -f /tmp/.bash_profile /home/rrisius/.bash_profile
    - file: path=/home/rrisius/.bash_profile owner=rrisius
    - action: shell cp -f /tmp/.bash_profile /home/kslaugh/.bash_profile
    - file: path=/home/kslaugh/.bash_profile owner=kslaugh

