---
- hosts: all
  sudo: True
  user: deploy 

  tasks:

  - name: Add ssh key and authorized user for Deploy user
    file: state=directory path=/home/deploy/.ssh/ owner=deploy group=admin mode=700    

  - copy: src=ssh/deploy/authorized_keys dest=/home/deploy/.ssh/authorized_keys owner=deploy group=admin mode=0640

  - copy: src=ssh/deploy/id_rsa dest=/home/deploy/.ssh/id_rsa owner=deploy group=admin mode=0600
 
  - copy: src=ssh/deploy/id_rsa.pub dest=/home/deploy/.ssh/id_rsa.pub owner=deploy group=admin mode=0640

