---
- hosts: oradev01.corp.ruan.com
  sudo: True
  user: root

  tasks:

  - action: template src=tns/tnsnames.dev dest=/u01/otmdb/oracle/product/11.2.0.4/network/admin/tnsnames.ora
  - file: path=/u01/otmdb/oracle/product/11.2.0.4/network/admin/tnsnames.ora owner=oracle group=oracle

- hosts: otmftidev01.corp.ruan.com
  sudo: True
  user: root

  tasks:

  - action: template src=tns/tnsnames.dev dest=/u01/otmdb/oracle/product/11.2.0.4/network/admin/tnsnames.ora
  - file: path=/u01/otmdb/oracle/product/11.2.0.4/network/admin/tnsnames.ora owner=oracle group=oracle


