---
- name: ensure apache is at the latest version
  yum: pkg=httpd state=latest

- name: Check if Firewall Allows port 80
  shell: "iptables -L | grep http"
  register: iptables_rule

- name: Allow port 80, If Rule Doesn't Exist
  command: firewall-cmd --permanent --zone=public --add-service=http 
  when: iptables_rule.stdout.find('http') != -1
  command: sudo firewall-cmd --reload
  when: iptables_rule.stdout.find('http') != -1
  
- name: write the apache config file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - restart apache

- name: ensure apache is running (and enable it at boot)
  service: name=httpd state=started enabled=yes
