---

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install the latest version of Fail2Ban
  yum: name=fail2ban state=latest

- name: install lynx - command line web browser
  yum: name=lynx state=present

