---

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install Gnome 3 Desktop
  command: yum -y groupinstall "Gnome desktop"
  when: ansible_distribution == "CentOS" 

- name: install the latest version of Fail2Ban
  yum: name=fail2ban state=latest

- name: install lynx - command line web browser
  yum: name=lynx state=present

- name: ensure latest version of VIM
  yum: name=vim state=latest

- name: copy accross personalized vim config
  copy: src=vimrc dest=/home/bmckenna/.vimrc owner=bmckenna mode=664

- name: copy accross personalized vim config
  copy: src=vimrc dest=/root/.vimrc owner=root mode=644

- name: install mlocate package - locate and updatedb
  yum: name=mlocate state=present

- name: install screen
  yum: name=screen state=present

- name: copy cmatrix screensaver to bmckenna home
  copy: src=cmatrix dest=/home/bmckenna/cmatrix owner=bmckenna mode=755

- name: install clusterssh
  yum: name=clusterssh state=present 
