---
- name: ensure apache is at the latest version
  yum: pkg=httpd state=latest
  when: ansible_os_family == "RedHat"

- name: ensure apache is at the latest version
  apt: pkg=httpd state=latest
  when: ansible_os_family == "Debian"

- name: ensure port 80 is open on the firewall
  firewalld: service=http permanent=true state=enabled immediate=yes
  notify:
  - restart firewalld

#- name: Check if firewall allows port 80
#  shell: "iptables -L | grep http"
#  register: iptables_rule
#
#- name: Allow port 80, If Rule Doesn't Exist
#  command: firewall-cmd --permanent --zone=public --add-service=http 
#  when: iptables_rule.stdout.find('http') != -1
#  command: sudo firewall-cmd --reload
#  when: iptables_rule.stdout.find('http') != -1
  

- name: write an emtpy apache welcome file, get rid of test page
  template: src=welcome.j2 dest=/etc/httpd/conf.d/welcome.conf

- name: write the apache config file
  template: src=httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - restart apache

- name: ensure apache is running (and enable it at boot)
  service: name=httpd state=started enabled=yes
