---
- name: install PHP packages
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
    - php
    - php5-mysql
    - php5-pdo
    - php5-gd
    - php5-mdstring
  when: ansible_os_family == "Red Hat"

- name: install PHP packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php
    - php5-mysql
    - php5-pdo
    - php5-gd
    - php5-mdstring
  when: ansible_os_family == "Debian"

- name: copy across a template for the php.info() page
  template: src=info.j2 dest=/var/www/html/info.php
