---
- name: Ensure latest NTP is installed
  yum: pkg=ntp state=latest
  when: ansible_os_family == "RedHat"

- name: Ensure latest NTP is installed
  apt: pkg=ntp state=latest
  when: ansible_os_family == "Debian"

- name: write NTP config file
  template: src=ntp.j2 dest=/etc/ntp.conf
  notify:
  - restart ntp
- name: ensure ntp is running on boot
  service: name=ntpd state=started enabled=yes

