---
- name: Make sure OpenSSH is at latest release
  yum: pkg=openssh state=latest
  when: ansible_os_family == "RedHat"

- name: Make sure OpenSSH is at latest release
  apt: pkg=openssh state=latest
  when: ansible_os_family == "Debian"

- name: write SSH config file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
  - restart sshd

